import m from 'mithril'
import LoginUI from './components/log-in'
import SignInUI from './components/sign-in'
import MainUI from './components/main'
import Authentication from './models/authentication'

// https://flems.io/#0=N4IgtglgJlA2CmIBcB2AnAOgCwoDQgGd4EBjAF3imRAFUiAnAMQHt6wMArAkfAMwgTckAbVAA7AIZhESWgwCyzKMU7d8JZmIpbqANwn0ABHXhGAvIeAAdMYbuHYEAmSSHhAXVw37D5hKgAMk4uhrwArmLkEJoAFACUlt4+9vTwZGH0tuypAI5h8M4x1rbJpdJkABZKrlYgAOIAogAqtV4lpT4ZsDUgFWRkAA4ESAD0I6lgALSpzpMSAxAYFabMANZh8wMYGmAj8xAjYQwErUkd9gDuEJUAwqnKWhASsMOGZPT5becAvnFnyRhKvAxDFwpEyNEQTMwrAyAliucfCZ6BhHM5DBZobCMFAJGQJP8fL9-t82v8SBlUlpXMBSf9YH4oK4wVFYtB4YSUmkMlkMLl8oUEYi7OUqkzDLVGi0eJzSl0en1BsMxhNpgUyHMFksVutNttmLt9odjiNaoYANSGaBfYWGK63e7AiHPV7vT6ywzE9oAoEglkQ2JYuGJb3nZHbSlOjGGIMer1EsneggSXTwZkRVkgjmhrnpTKGbLwPLqooenyi6oSkAABRo0ptwvlVcVQ1G43gUxmGv22voaw2Ay2Oz2C2NpgIppAFuMDAj9CpZAw1rL9lx+Nc4Yp86dDcR9oqd0oTqeL1cbvgu6Jf293xs3x4hGI8EzQhAAAYkABGABMIFJ4ikGQ5FMIJnFUB8NC0J09AMGcQOCaMhTsTQIDEa4N1nBl-FAshd10CB4AudNwUheIQ3OVI8yyGJagwI5TEmNEyFaOCUSYjAwHmUEMwDEF6PobNbRjbl8zAGiQAkOiGEY4JJmuDsWOACpUl4HoRkoa5J2nfilygXBDE0EhUjxNMCz5ZgwgoVFUNWUlDB0-h6GcAA5QDpzNM1LR02AJBcwDrx+OIAvsW8xHvf8QEkaRqGRFg2HA9RNG0MgYKMWLWDARD-hQtCQn9UjdDEJR4HhcMsKgGJCuKjA8XeAhdLiOlvXwwjiMzMikOSSieQLcTeAyxSV1KTQCDCAAjSA8p40iSvIoSOngDABlSVMtAAEXgXgJBhMh4iGxFw2TVM9pzYVQqEuzhH2sTah8saVDu4gWNqRgICcshDCi+BajiS8OhukBUIGSylzEYGyGEMgAE8BngMwKAADzIdxhAGHySHgKpYGUegzFe97PsA9xBtOxEcvB1x2H3ABBfp6HE-RYHyFj8tiRn8lK2ctwXDBHL86Ro3Z+Bfj+4UhYw0w5x5vmyFc6R9pF67xMe2BUQke7YGekAAl8j6vp+0XkgBoGQZNiG0YkDGsZxswdfRL7iZ4Ob5oMtCwcsymMBpumGeeZmndZkEhc5yXuadNX+fgQW-eF379p8cXWKl8OfMjhW49J8txLGyyyE0DAc-6TRIZhuHRom65Hf02oAGUU2+kAM-OdxgrsUL73wIhSF418ADYkAAZk-P9cAA6LZB1qGLMXLgIKS6DZH0IxJ+nrLmoIojQmmtmiuUQSOm60TxM41C1anyyWKuzP7AByRdA44Ewkv+Ob-Egknc6l3lM21wAHIRiYr-Q2wpDLGQoJ7PsllFqODEKsF+bdq7AScj9faLdgGv1qEQTMLEqrKG2BUAQUAqSt2SC3Ekd4R5jyAnqWeiUoI6FkNkaei1lqbQgAjGIv8ADEv9rxMKgTEKAzAKTSC0AXJQUNEEAOCCTHwtRpHOFqDSD0VIcZtV4h1fah9qIr0svpMSyIcJBTjCSXc8iNJkBGEgaASjnZdWBGoreJEd7FX3sKbRvVdG4V6ulNg+lcGLVqk5YxpNzohTaL8ShkVALUG2AQNQIBILJWoGNCRuBQbg3SYXPOthgD9WpEVNgzxDCfl7gMBGhgABqphcSSAANycXoAAc1Qq4b8b5ymhRsGfVewBGktLEF+DpFTtp5waRIBGkwrhQEqEMt8wy6mhQfmIMIlh+mtLfIYTZA8FldLEFJBiTFLBMUmM4KGCAkBFTEPAcZzSNlbJKQsgY-goCoSaUgN8izun8RkrMeSmVgBjUtqsJpkCxBMi4VtKFEg6mpPoGoz85TDAEGYI4KAhguEwCgHUjQDJ6BIC4QPIldTXkEAtlDJAY0GQkFWLcgZHyHmIoRnU55MA3lIAABxIs-AAVnKXUxGGplAaHoHiSElzNA3KWT8k5-ykBVFTEYYAgrJjCtYGKzQSAIg4xgVKmw3SVaWFJeSyl1LaXrMGZszZfLmVLLNpYOFCKkUorRRirFsLWA42mP4CARxB78tSZMggEAABe7LHUMUDSSpwJqqXCPNQYelVrHn8tZa8sQ7zPzDJKTaup0zZlZrfAAUi+fs7JmgHXAtBRZcFBL4D1o9fC0wX5nWougG6mAjavWiteX6ge-LcWsAJUSge0ayU+QpahXVkw400rpfczZWbU0vPZUuipvL+UqrVaK3iErrmloLrnTVCrTCVppdW7VdaOXwGvRyxZf5PAgBgasIQohonj3ANcZSAgHxdGoC2ZUhwwYgv1LsSa37YAAAFPwYBg73EY4H6ACASiAaGsNqAECMhAAYKVvjuG+EAA

// TODO: implement: mandatory/optional email + email verification + password reset? (server-side)
// TODO: un component Title/breadcrumb pour DRY les m('h1', [...]) ?
;(async () => {
  await Authentication.load()

  m.route(document.body, Authentication.isAuthenticated ? '/main' : '/login' , {
    '/login': LoginUI,
    '/sign-in': SignInUI,
    '/main': MainUI,
  })
})()
